language: c

before_install:
  - sudo apt-get update -qq
  - #sudo apt-get install -qq gauche
  - wget http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gauche/libgauche-0.9-0_0.9.4-5_amd64.deb
  - wget http://us.archive.ubuntu.com/ubuntu/pool/universe/g/gauche/gauche_0.9.4-5_amd64.deb
  - sudo dpkg -i libgauche-0.9-0_0.9.4-5_amd64.deb gauche_0.9.4-5_amd64.deb 
  - gosh -V

script:
 - make test
